### PR TITLE
fix: new cmd with quote description

### LINKED ISSUE #45: `maltmill new` generates invalid formula when repo description contains a single quote
## Summary
When a GitHub repo description includes a single quote (`'`), `maltmill new` renders the Homebrew formula with `desc '...'` and produces an invalid string.

## Steps to reproduce
1. Use a repo with a description containing a single quote, e.g. "A CLI that's fast".
2. Run `maltmill new <owner>/<repo>`.
3. Inspect the generated formula.

## Actual behavior
The formula contains:
```rb
desc 'A CLI that's fast'
```
This breaks the Ruby string and the formula is invalid.

## Expected behavior
`desc` should be escaped so the formula is valid:
```rb
desc 'A CLI that\'s fast'
```

## Environment
- maltmill version: 1.2.0
- OS: Mac

## Suggested fix
Escape single quotes (and backslashes) in the description before rendering the template.

### PR DESCRIPTION
**Pull request by jackchuka**
fixes https://github.com/Songmu/maltmill/issues/45

### CODE REVIEW

File: cmd_new.go [hunk 1]
```diff
@@ -100,7 +100,21 @@ type formulaDownload struct {
...
+	}
+	// Escape backslashes first to avoid double escaping.
+	in = strings.ReplaceAll(in, "\\", "\\\\")
+	in = strings.ReplaceAll(in, "'", "\\'")
+	return in
+}
+
+var formulaTmpl = template.Must(
+	template.New("formulaTmpl").Funcs(template.FuncMap{
+		"escapeDesc": escapeDescd,
```
Comment (Songmu) [inline cmd_new.go]: Nice catch! We might use this in other places as well, so could you rename the function to `escapeSingleQuotes`?

**Review by Songmu — CHANGES_REQUESTED** [review]

File: cmd_new.go (hunk 1 above)
Comment (jackchuka) [reply cmd_new.go]: sounds good 👍 
I've addressed in [88d6f75](https://github.com/Songmu/maltmill/pull/46/commits/88d6f75d7b867af94a0035de54bceb00f3eb3b83)

**Review by Songmu — APPROVED** [review]
